version: '3'

services:
  rails:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    command: bin/rails s

volumes:
  bundle:
